package org.module.mapper.system.user;

import org.module.model.system.user.SmUesrRole;

public interface SmUesrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    int insert(SmUesrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    int insertSelective(SmUesrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    SmUesrRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmUesrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_uesr_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmUesrRole record);
}