package org.system.module.mapper.server;

import org.system.module.model.server.SmServer;

public interface SmServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int insert(SmServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int insertSelective(SmServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    SmServer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmServer record);
}