package org.module.model.commons.db;

import java.util.Date;

public class CmColumnType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.en_name
     *
     * @mbggenerated
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.value_area
     *
     * @mbggenerated
     */
    private String valueArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.id
     *
     * @return the value of cm_column_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.id
     *
     * @param id the value for cm_column_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.uid
     *
     * @return the value of cm_column_type.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.uid
     *
     * @param uid the value for cm_column_type.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.code
     *
     * @return the value of cm_column_type.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.code
     *
     * @param code the value for cm_column_type.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.name
     *
     * @return the value of cm_column_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.name
     *
     * @param name the value for cm_column_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.en_name
     *
     * @return the value of cm_column_type.en_name
     *
     * @mbggenerated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.en_name
     *
     * @param enName the value for cm_column_type.en_name
     *
     * @mbggenerated
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.value_area
     *
     * @return the value of cm_column_type.value_area
     *
     * @mbggenerated
     */
    public String getValueArea() {
        return valueArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.value_area
     *
     * @param valueArea the value for cm_column_type.value_area
     *
     * @mbggenerated
     */
    public void setValueArea(String valueArea) {
        this.valueArea = valueArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.comment
     *
     * @return the value of cm_column_type.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.comment
     *
     * @param comment the value for cm_column_type.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.create_user
     *
     * @return the value of cm_column_type.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.create_user
     *
     * @param createUser the value for cm_column_type.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.create_time
     *
     * @return the value of cm_column_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.create_time
     *
     * @param createTime the value for cm_column_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.update_user
     *
     * @return the value of cm_column_type.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.update_user
     *
     * @param updateUser the value for cm_column_type.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column_type.update_time
     *
     * @return the value of cm_column_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column_type.update_time
     *
     * @param updateTime the value for cm_column_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}