package org.module.model.commons.db;

import java.util.Date;

public class CmColumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.type_code
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.length
     *
     * @mbggenerated
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.default_value
     *
     * @mbggenerated
     */
    private String defaultValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.table_code
     *
     * @mbggenerated
     */
    private String tableCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.db_code
     *
     * @mbggenerated
     */
    private String dbCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.db_name
     *
     * @mbggenerated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_column.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.id
     *
     * @return the value of cm_column.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.id
     *
     * @param id the value for cm_column.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.uid
     *
     * @return the value of cm_column.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.uid
     *
     * @param uid the value for cm_column.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.code
     *
     * @return the value of cm_column.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.code
     *
     * @param code the value for cm_column.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.name
     *
     * @return the value of cm_column.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.name
     *
     * @param name the value for cm_column.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.type_code
     *
     * @return the value of cm_column.type_code
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.type_code
     *
     * @param typeCode the value for cm_column.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.type_name
     *
     * @return the value of cm_column.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.type_name
     *
     * @param typeName the value for cm_column.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.length
     *
     * @return the value of cm_column.length
     *
     * @mbggenerated
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.length
     *
     * @param length the value for cm_column.length
     *
     * @mbggenerated
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.comment
     *
     * @return the value of cm_column.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.comment
     *
     * @param comment the value for cm_column.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.default_value
     *
     * @return the value of cm_column.default_value
     *
     * @mbggenerated
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.default_value
     *
     * @param defaultValue the value for cm_column.default_value
     *
     * @mbggenerated
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.table_code
     *
     * @return the value of cm_column.table_code
     *
     * @mbggenerated
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.table_code
     *
     * @param tableCode the value for cm_column.table_code
     *
     * @mbggenerated
     */
    public void setTableCode(String tableCode) {
        this.tableCode = tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.table_name
     *
     * @return the value of cm_column.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.table_name
     *
     * @param tableName the value for cm_column.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.db_code
     *
     * @return the value of cm_column.db_code
     *
     * @mbggenerated
     */
    public String getDbCode() {
        return dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.db_code
     *
     * @param dbCode the value for cm_column.db_code
     *
     * @mbggenerated
     */
    public void setDbCode(String dbCode) {
        this.dbCode = dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.db_name
     *
     * @return the value of cm_column.db_name
     *
     * @mbggenerated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.db_name
     *
     * @param dbName the value for cm_column.db_name
     *
     * @mbggenerated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.create_user
     *
     * @return the value of cm_column.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.create_user
     *
     * @param createUser the value for cm_column.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.create_time
     *
     * @return the value of cm_column.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.create_time
     *
     * @param createTime the value for cm_column.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.update_user
     *
     * @return the value of cm_column.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.update_user
     *
     * @param updateUser the value for cm_column.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_column.update_time
     *
     * @return the value of cm_column.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_column.update_time
     *
     * @param updateTime the value for cm_column.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}