package org.module.model.commons.db;

import java.util.Date;

public class CmTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.db_code
     *
     * @mbggenerated
     */
    private String dbCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.db_name
     *
     * @mbggenerated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.engine
     *
     * @mbggenerated
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_table.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.id
     *
     * @return the value of cm_table.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.id
     *
     * @param id the value for cm_table.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.uid
     *
     * @return the value of cm_table.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.uid
     *
     * @param uid the value for cm_table.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.code
     *
     * @return the value of cm_table.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.code
     *
     * @param code the value for cm_table.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.name
     *
     * @return the value of cm_table.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.name
     *
     * @param name the value for cm_table.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.comment
     *
     * @return the value of cm_table.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.comment
     *
     * @param comment the value for cm_table.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.db_code
     *
     * @return the value of cm_table.db_code
     *
     * @mbggenerated
     */
    public String getDbCode() {
        return dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.db_code
     *
     * @param dbCode the value for cm_table.db_code
     *
     * @mbggenerated
     */
    public void setDbCode(String dbCode) {
        this.dbCode = dbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.db_name
     *
     * @return the value of cm_table.db_name
     *
     * @mbggenerated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.db_name
     *
     * @param dbName the value for cm_table.db_name
     *
     * @mbggenerated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.engine
     *
     * @return the value of cm_table.engine
     *
     * @mbggenerated
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.engine
     *
     * @param engine the value for cm_table.engine
     *
     * @mbggenerated
     */
    public void setEngine(String engine) {
        this.engine = engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.create_user
     *
     * @return the value of cm_table.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.create_user
     *
     * @param createUser the value for cm_table.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.create_time
     *
     * @return the value of cm_table.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.create_time
     *
     * @param createTime the value for cm_table.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.update_user
     *
     * @return the value of cm_table.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.update_user
     *
     * @param updateUser the value for cm_table.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_table.update_time
     *
     * @return the value of cm_table.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_table.update_time
     *
     * @param updateTime the value for cm_table.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}