package org.module.mapper.product;

import org.module.model.product.PmDefine;

public interface PmDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    int insert(PmDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    int insertSelective(PmDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    PmDefine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmDefine record);
}