package org.module.mapper.product;

import org.module.model.product.PmProductDrafts;

public interface PmProductDraftsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int insert(PmProductDrafts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int insertSelective(PmProductDrafts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    PmProductDrafts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmProductDrafts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PmProductDrafts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_drafts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmProductDrafts record);
}