package org.module.mapper.product;

import org.module.model.product.PmProductInfo;

public interface PmProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    int insert(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    int insertSelective(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    PmProductInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmProductInfo record);
}