package org.module.mapper.product;

import org.module.model.product.PmSkuInfo;

public interface PmSkuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    int insert(PmSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    int insertSelective(PmSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    PmSkuInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PmSkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sku_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PmSkuInfo record);
}