package org.system.mapper.menu;

import org.system.model.menu.SmMenuPermission;

public interface SmMenuPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int insert(SmMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int insertSelective(SmMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    SmMenuPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmMenuPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmMenuPermission record);
}