package org.system.mapper.menu;

import org.system.model.menu.SmMenu;

public interface SmMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insert(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int insertSelective(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    SmMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmMenu record);
}