package org.module.mapper.commons.db;

import org.module.commons.model.db.CmColumn;

public interface CmColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    int insert(CmColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    int insertSelective(CmColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    CmColumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmColumn record);
}