package org.module.mapper.commons.db;

import org.module.model.commons.db.CmDatabase;

public interface CmDatabaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    int insert(CmDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    int insertSelective(CmDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    CmDatabase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_database
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmDatabase record);
}