package org.module.mapper.commons.db;

import org.module.commons.model.db.CmIndex;

public interface CmIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    int insert(CmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    int insertSelective(CmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    CmIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmIndex record);
}