package org.module.mapper.commons.db;

import org.module.commons.model.db.CmIndexType;

public interface CmIndexTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    int insert(CmIndexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    int insertSelective(CmIndexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    CmIndexType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmIndexType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_index_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmIndexType record);
}