package org.module.mapper.commons.db;

import org.module.model.commons.db.CmTableConstraintsType;

public interface CmTableConstraintsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    int insert(CmTableConstraintsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    int insertSelective(CmTableConstraintsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    CmTableConstraintsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmTableConstraintsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table_constraints_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmTableConstraintsType record);
}