package org.module.mapper.commons.db;

import org.module.commons.model.db.CmTable;

public interface CmTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    int insert(CmTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    int insertSelective(CmTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    CmTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmTable record);
}