package org.system.model.menu;

import java.util.Date;

public class SmMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.parent_code
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.group_code
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.flag_able
     *
     * @mbggenerated
     */
    private Integer flagAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_menu.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.id
     *
     * @return the value of sm_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.id
     *
     * @param id the value for sm_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.uid
     *
     * @return the value of sm_menu.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.uid
     *
     * @param uid the value for sm_menu.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.code
     *
     * @return the value of sm_menu.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.code
     *
     * @param code the value for sm_menu.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.parent_code
     *
     * @return the value of sm_menu.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.parent_code
     *
     * @param parentCode the value for sm_menu.parent_code
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.group_code
     *
     * @return the value of sm_menu.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.group_code
     *
     * @param groupCode the value for sm_menu.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.name
     *
     * @return the value of sm_menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.name
     *
     * @param name the value for sm_menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.url
     *
     * @return the value of sm_menu.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.url
     *
     * @param url the value for sm_menu.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.flag_able
     *
     * @return the value of sm_menu.flag_able
     *
     * @mbggenerated
     */
    public Integer getFlagAble() {
        return flagAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.flag_able
     *
     * @param flagAble the value for sm_menu.flag_able
     *
     * @mbggenerated
     */
    public void setFlagAble(Integer flagAble) {
        this.flagAble = flagAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.create_user
     *
     * @return the value of sm_menu.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.create_user
     *
     * @param createUser the value for sm_menu.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.create_time
     *
     * @return the value of sm_menu.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.create_time
     *
     * @param createTime the value for sm_menu.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.update_user
     *
     * @return the value of sm_menu.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.update_user
     *
     * @param updateUser the value for sm_menu.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_menu.update_time
     *
     * @return the value of sm_menu.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_menu.update_time
     *
     * @param updateTime the value for sm_menu.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}