package org.system.mapper.server;

import org.system.model.server.SmServerGroup;

public interface SmServerGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    int insert(SmServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    int insertSelective(SmServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    SmServerGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_server_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmServerGroup record);
}