package org.module.commons.model.db;

import java.util.Date;

public class CmDatabase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.en_name
     *
     * @mbggenerated
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.initial_size
     *
     * @mbggenerated
     */
    private Integer initialSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.max_active
     *
     * @mbggenerated
     */
    private Integer maxActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.min_idle
     *
     * @mbggenerated
     */
    private Integer minIdle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.max_wait
     *
     * @mbggenerated
     */
    private Integer maxWait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.test_on_borrow
     *
     * @mbggenerated
     */
    private Integer testOnBorrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.test_on_return
     *
     * @mbggenerated
     */
    private Integer testOnReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.test_while_idle
     *
     * @mbggenerated
     */
    private Integer testWhileIdle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.time_between_eviction_runs_millis
     *
     * @mbggenerated
     */
    private Integer timeBetweenEvictionRunsMillis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.min_evictable_idle_time_millis
     *
     * @mbggenerated
     */
    private Integer minEvictableIdleTimeMillis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.remove_abandoned
     *
     * @mbggenerated
     */
    private Integer removeAbandoned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.remove_abandoned_timeout
     *
     * @mbggenerated
     */
    private Integer removeAbandonedTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.log_abandoned
     *
     * @mbggenerated
     */
    private Integer logAbandoned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.filters
     *
     * @mbggenerated
     */
    private String filters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_database.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.id
     *
     * @return the value of cm_database.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.id
     *
     * @param id the value for cm_database.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.uid
     *
     * @return the value of cm_database.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.uid
     *
     * @param uid the value for cm_database.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.code
     *
     * @return the value of cm_database.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.code
     *
     * @param code the value for cm_database.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.name
     *
     * @return the value of cm_database.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.name
     *
     * @param name the value for cm_database.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.en_name
     *
     * @return the value of cm_database.en_name
     *
     * @mbggenerated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.en_name
     *
     * @param enName the value for cm_database.en_name
     *
     * @mbggenerated
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.url
     *
     * @return the value of cm_database.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.url
     *
     * @param url the value for cm_database.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.username
     *
     * @return the value of cm_database.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.username
     *
     * @param username the value for cm_database.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.password
     *
     * @return the value of cm_database.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.password
     *
     * @param password the value for cm_database.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.initial_size
     *
     * @return the value of cm_database.initial_size
     *
     * @mbggenerated
     */
    public Integer getInitialSize() {
        return initialSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.initial_size
     *
     * @param initialSize the value for cm_database.initial_size
     *
     * @mbggenerated
     */
    public void setInitialSize(Integer initialSize) {
        this.initialSize = initialSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.max_active
     *
     * @return the value of cm_database.max_active
     *
     * @mbggenerated
     */
    public Integer getMaxActive() {
        return maxActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.max_active
     *
     * @param maxActive the value for cm_database.max_active
     *
     * @mbggenerated
     */
    public void setMaxActive(Integer maxActive) {
        this.maxActive = maxActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.min_idle
     *
     * @return the value of cm_database.min_idle
     *
     * @mbggenerated
     */
    public Integer getMinIdle() {
        return minIdle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.min_idle
     *
     * @param minIdle the value for cm_database.min_idle
     *
     * @mbggenerated
     */
    public void setMinIdle(Integer minIdle) {
        this.minIdle = minIdle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.max_wait
     *
     * @return the value of cm_database.max_wait
     *
     * @mbggenerated
     */
    public Integer getMaxWait() {
        return maxWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.max_wait
     *
     * @param maxWait the value for cm_database.max_wait
     *
     * @mbggenerated
     */
    public void setMaxWait(Integer maxWait) {
        this.maxWait = maxWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.test_on_borrow
     *
     * @return the value of cm_database.test_on_borrow
     *
     * @mbggenerated
     */
    public Integer getTestOnBorrow() {
        return testOnBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.test_on_borrow
     *
     * @param testOnBorrow the value for cm_database.test_on_borrow
     *
     * @mbggenerated
     */
    public void setTestOnBorrow(Integer testOnBorrow) {
        this.testOnBorrow = testOnBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.test_on_return
     *
     * @return the value of cm_database.test_on_return
     *
     * @mbggenerated
     */
    public Integer getTestOnReturn() {
        return testOnReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.test_on_return
     *
     * @param testOnReturn the value for cm_database.test_on_return
     *
     * @mbggenerated
     */
    public void setTestOnReturn(Integer testOnReturn) {
        this.testOnReturn = testOnReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.test_while_idle
     *
     * @return the value of cm_database.test_while_idle
     *
     * @mbggenerated
     */
    public Integer getTestWhileIdle() {
        return testWhileIdle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.test_while_idle
     *
     * @param testWhileIdle the value for cm_database.test_while_idle
     *
     * @mbggenerated
     */
    public void setTestWhileIdle(Integer testWhileIdle) {
        this.testWhileIdle = testWhileIdle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.time_between_eviction_runs_millis
     *
     * @return the value of cm_database.time_between_eviction_runs_millis
     *
     * @mbggenerated
     */
    public Integer getTimeBetweenEvictionRunsMillis() {
        return timeBetweenEvictionRunsMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.time_between_eviction_runs_millis
     *
     * @param timeBetweenEvictionRunsMillis the value for cm_database.time_between_eviction_runs_millis
     *
     * @mbggenerated
     */
    public void setTimeBetweenEvictionRunsMillis(Integer timeBetweenEvictionRunsMillis) {
        this.timeBetweenEvictionRunsMillis = timeBetweenEvictionRunsMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.min_evictable_idle_time_millis
     *
     * @return the value of cm_database.min_evictable_idle_time_millis
     *
     * @mbggenerated
     */
    public Integer getMinEvictableIdleTimeMillis() {
        return minEvictableIdleTimeMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.min_evictable_idle_time_millis
     *
     * @param minEvictableIdleTimeMillis the value for cm_database.min_evictable_idle_time_millis
     *
     * @mbggenerated
     */
    public void setMinEvictableIdleTimeMillis(Integer minEvictableIdleTimeMillis) {
        this.minEvictableIdleTimeMillis = minEvictableIdleTimeMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.remove_abandoned
     *
     * @return the value of cm_database.remove_abandoned
     *
     * @mbggenerated
     */
    public Integer getRemoveAbandoned() {
        return removeAbandoned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.remove_abandoned
     *
     * @param removeAbandoned the value for cm_database.remove_abandoned
     *
     * @mbggenerated
     */
    public void setRemoveAbandoned(Integer removeAbandoned) {
        this.removeAbandoned = removeAbandoned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.remove_abandoned_timeout
     *
     * @return the value of cm_database.remove_abandoned_timeout
     *
     * @mbggenerated
     */
    public Integer getRemoveAbandonedTimeout() {
        return removeAbandonedTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.remove_abandoned_timeout
     *
     * @param removeAbandonedTimeout the value for cm_database.remove_abandoned_timeout
     *
     * @mbggenerated
     */
    public void setRemoveAbandonedTimeout(Integer removeAbandonedTimeout) {
        this.removeAbandonedTimeout = removeAbandonedTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.log_abandoned
     *
     * @return the value of cm_database.log_abandoned
     *
     * @mbggenerated
     */
    public Integer getLogAbandoned() {
        return logAbandoned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.log_abandoned
     *
     * @param logAbandoned the value for cm_database.log_abandoned
     *
     * @mbggenerated
     */
    public void setLogAbandoned(Integer logAbandoned) {
        this.logAbandoned = logAbandoned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.filters
     *
     * @return the value of cm_database.filters
     *
     * @mbggenerated
     */
    public String getFilters() {
        return filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.filters
     *
     * @param filters the value for cm_database.filters
     *
     * @mbggenerated
     */
    public void setFilters(String filters) {
        this.filters = filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.create_user
     *
     * @return the value of cm_database.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.create_user
     *
     * @param createUser the value for cm_database.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.create_time
     *
     * @return the value of cm_database.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.create_time
     *
     * @param createTime the value for cm_database.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.update_user
     *
     * @return the value of cm_database.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.update_user
     *
     * @param updateUser the value for cm_database.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.update_time
     *
     * @return the value of cm_database.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.update_time
     *
     * @param updateTime the value for cm_database.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_database.desc
     *
     * @return the value of cm_database.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_database.desc
     *
     * @param desc the value for cm_database.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}