package org.system.mapper.role;

import org.system.model.role.SmRolePermission;

public interface SmRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    int insert(SmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(SmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    SmRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRolePermission record);
}