package org.system.mapper.role;

import org.system.model.role.SmRole;

public interface SmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int insert(SmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int insertSelective(SmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    SmRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRole record);
}